@startuml
'https://plantuml.com/class-diagram

Rover }-- Plateau
Rover -- Direction

Error -- Plateau
Error -- Rover

class Plateau {
- X_MIN: int = 0
- Y_MIN: int = 0
- X_MAX: int
- Y_MAX: int

+ Plateau(x: int, y: int): void
+ move(x: int, y: int, d: Direction): errorMsg
- collisionCheck(): errorMsg
- edgeCheck(): errorMsg
}

class Rover {
- SPEED: int = 1
- posX: int
- posY: int
- d: Direction

+ Rover(x: int, y: int, d: Direction, speed: int)
+ processMovement(movement: String) : errorMsg
- goLeft()
- goRight()
- move(d: Direction): errorMsg
}

enum Error {
    ERROR_OVER_EDGE,
    ERROR_TAKEN_SPOT
}

enum Direction {
NORTH,
EAST,
SOUTH,
WEST
}

@enduml